POST http://localhost:5069/register
content-Type: application/json

{
    "Username": "verytestuser",
    "Email": "verytestuser@realemail.com",
    "Password": "nicepassword",
    "FirstName": "John",
    "LastName": "Doe",
    "PhoneNumber": "1234567890"
}

### Ir sitas returnina tokena su kuriuo poto gali autorizuotis pasiimant kitus requestus

POST http://localhost:5069/login
Content-Type: application/json

{
    "Username": "verytestuser",
    "Password": "nicepassword"
}

### Updating, tu fieldu kuriu nereikia updatinti gali tiesiog nesiusti
PUT http://localhost:5069/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidmVyeXRlc3R1c2VyIiwic3ViIjoidmVyeXRlc3R1c2VyIiwiZW1haWwiOiJ2ZXJ5dGVzdHVzZXJAcmVhbGVtYWlsLmNvbSIsImp0aSI6IjNlNTlhMWZjLWFiYmQtNDk1My04NTk1LTNhNjZhNjJiMDg4YiIsImV4cCI6MTcyOTE0Njg4NSwiaXNzIjoieW91cmRvbWFpbi5jb20iLCJhdWQiOiJ5b3VyZG9tYWluLmNvbSJ9.83gICXCm5sqc91Ffh2eM9BzOcPl7Sgon5sIajC6pSPk
Content-Type: application/json

{
    "FirstName": "Le-Bronius",
    "LastName": "Dzheimsas",
    "PhoneNumber": "6942069420",
    "Email": "newemail@domain.com",
    "Password": "newsecurepassword"
}


###
POST http://localhost:5069/announce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidmVyeXRlc3R1c2VyIiwic3ViIjoidmVyeXRlc3R1c2VyIiwiZW1haWwiOiJ2ZXJ5dGVzdHVzZXJAcmVhbGVtYWlsLmNvbSIsImp0aSI6IjNlNTlhMWZjLWFiYmQtNDk1My04NTk1LTNhNjZhNjJiMDg4YiIsImV4cCI6MTcyOTE0Njg4NSwiaXNzIjoieW91cmRvbWFpbi5jb20iLCJhdWQiOiJ5b3VyZG9tYWluLmNvbSJ9.83gICXCm5sqc91Ffh2eM9BzOcPl7Sgon5sIajC6pSPk
Content-Type: application/json

{
    "role": "driver"
}


### Cia tiesiog prasicheckint gali ar tokenas valid.
GET http://localhost:5069/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidmVyeXRlc3R1c2VyIiwic3ViIjoidmVyeXRlc3R1c2VyIiwiZW1haWwiOiJ2ZXJ5dGVzdHVzZXJAcmVhbGVtYWlsLmNvbSIsImp0aSI6IjNlNTlhMWZjLWFiYmQtNDk1My04NTk1LTNhNjZhNjJiMDg4YiIsImV4cCI6MTcyOTE0Njg4NSwiaXNzIjoieW91cmRvbWFpbi5jb20iLCJhdWQiOiJ5b3VyZG9tYWluLmNvbSJ9.83gICXCm5sqc91Ffh2eM9BzOcPl7Sgon5sIajC6pSPk

### Returnina visus siandiens announcementus
GET http://localhost:5069/announcements/today
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidmVyeXRlc3R1c2VyIiwic3ViIjoidmVyeXRlc3R1c2VyIiwiZW1haWwiOiJ2ZXJ5dGVzdHVzZXJAcmVhbGVtYWlsLmNvbSIsImp0aSI6IjNlNTlhMWZjLWFiYmQtNDk1My04NTk1LTNhNjZhNjJiMDg4YiIsImV4cCI6MTcyOTE0Njg4NSwiaXNzIjoieW91cmRvbWFpbi5jb20iLCJhdWQiOiJ5b3VyZG9tYWluLmNvbSJ9.83gICXCm5sqc91Ffh2eM9BzOcPl7Sgon5sIajC6pSPk
